pion/mediadevices

- pkg/driver/camera_linux.go
Stop stream only if started and close webcam.Webcam.
This sometimes caused unstable behavior of the camera.
> Fix camera close

- pkg/codec/openh264/openh264.go
- pkg/codec/vpx/vpx.go
- pkg/io/video/convert.go
Moved I420 converter from vpx.go, converted `video.Reader` in openh264.go, and created ToI420 to convert a `video.Reader` to a new `video.Reader` that will emit images in I420 format.
> Add ToI420 converter

- examples/simple/main.go
- track.go
In Web API, `MediaStreamTrack.ended` event is fired and
`MediaStreamTrack.onended` handler is called on device error.
This commit adds same way to handle errors.
Fixes #18
> Add OnEnded handler

- examples/simple/main.go
- mediadevices.go
- mediastreamconstraints.go
- pkg/codec/registrar.go
- pkg/prop/prop.go
- track.go
It feels weird to put `Codec` under `MediaTrackConstraints`. Figured that it makes to put it under `prop.Codec` instead.
> Move Codec from MediaTrackConstraints to prop.Codec

- mediadevices.go
- sampler.go
- track.go
Add WithTrackGenerator option to specify TrackGenerator.
This allows user to replace Track by user defined one that
has WriteSample() and Codec() interface.
So that we can get encoded media streams directly from MediaDevices.
> Allow to use user defined Track

- pkg/driver/camera/camera_bench_test.go
- pkg/driver/camera/camera_linux.go
- track.go
Treat camera read timeout as error and return detailed errors.
Wait finishing video read loop to avoid memory violation
as the video frames might be alloced by C or on shared memory.
https://github.com/pion/mediadevices/issues/35#issuecomment-584535022
> Stop video track safely

- pkg/driver/screen/x11_linux.go
- pkg/driver/screen/x11capture_linux.go
- pkg/io/video/convert.go
- pkg/io/video/convert_test.go
- Fix R-B byte order in screen capture
- Set image metadata everytime in screen capture
- Fix pixel format conversion from I444
Fixed version:
> Fix color conversions

- pkg/codec/openh264/bridge.cpp
Before openh264 expected to get I444. But, since we now convert the reader to I420, the chroma stride that it's being used in C++ is no longer correct.
> Fix openh264 incorrect chroma stride

- pkg/codec/vpx/vpx.go
ulong and u_char are old name and are not available on musl libc.
fixes regression from #60
> Fix non-standard C types

- pkg/driver/videotest/dummy.go
It took too much CPU time.
Cache fixed region to reduce CPU usage.
> Refactor videotest driver

- pkg/io/video/convert.go
- pkg/io/video/convert_cgo.c
- pkg/io/video/convert_cgo.go
- pkg/io/video/convert_cgo.h
- pkg/io/video/convert_cgo_test.go
- pkg/io/video/convert_test.go
```
BenchmarkToI420/480p/I444-4         	   17209	    238,403 ns/op
BenchmarkToI420/480p/I422-4         	   24540	    148,271 ns/op
BenchmarkToI420/1080p/I444-4        	    2365	  1,397,549 ns/op
BenchmarkToI420/1080p/I422-4        	    4168	    816,333 ns/op
BenchmarkToI420CGO/NoCGO/480p/I444-4             5720	    570,723 ns/op
BenchmarkToI420CGO/NoCGO/480p/I422-4             8224	    432,129 ns/op
BenchmarkToI420CGO/NoCGO/1080p/I444-4             997	  3,480,059 ns/op
BenchmarkToI420CGO/NoCGO/1080p/I422-4            1335	  2,602,584 ns/op
```
with `CGO_CFLAGS=-march=native -O3`
```
BenchmarkToI420/480p/I444-4         	   47775	     73,395 ns/op
BenchmarkToI420/480p/I422-4         	  109963	     32,822 ns/op
BenchmarkToI420/1080p/I444-4        	    8026	    484,568 ns/op …
```
> Add CGO version of color convert

- track.go
- track_test.go
OnEnded handler was not called if something errored before
registering the handler. Store error and call handler immediately
on handler registration.
> Call OnEnded even if errored before register

- mediadevices.go
- mediadevices_test.go
- pkg/driver/audiotest/dummy.go
- pkg/driver/camera/camera_linux.go
- pkg/driver/screen/x11_linux.go
- pkg/driver/videotest/dummy.go
- pkg/driver/wrapper.go
- track.go
In GetUserMedia and GetDisplayMedia, driver was left opened if
initialization failure. Since Trackers are not returned on error,
there was no way to close them.
This commit closes Trackers on GetUserMedia/GetDisplayMedia failure.
Fixes #74
> Close drivers on stream initialization failure

- pkg/driver/wrapper.go
- pkg/driver/wrapper_test.go
In https://github.com/pion/mediadevices/pull/75, we forgot to add the same automatic close for `AudioRecord`. I also added some unit tests to check this.
> Fix AudioRecord automatic close when failed

- mediadevices.go
- pkg/prop/prop.go
- pkg/prop/prop_test.go
This PR contains an alternative approach to https://github.com/pion/mediadevices/pull/71.
Resolves https://github.com/pion/mediadevices/issues/61
* Add a Merge method in prop
* Replace a manual merge in mediadevices in best property selection with the new Merge method
> Add support for non-discrete constraints

- pkg/driver/camera/camera.go
- pkg/driver/microphone/microphone.go
- pkg/driver/screen/screen.go
Hi, maintainers! 
I was building the library on macOS but the following error caused.
```
build github.com/pion/mediadevices/pkg/driver/camera: cannot load github.com/pion/mediadevices/pkg/driver/camera: no Go source files
```
So I'd like to place the empty package files to make it buildable on any platform, thank you!
> Add default package file for drivers

- pkg/codec/openh264/bridge.cpp
- pkg/codec/openh264/bridge.hpp
- pkg/codec/openh264/error.go
- pkg/codec/openh264/openh264.go
Errno based error handling is not goroutine safe on Darwin.
Receive error number as int pointer and wrap by error interface.
> Fix CGO error handling of openh264 codec

- go.mod
- go.sum
- pkg/codec/opus/opus.go
I created a fork of https://github.com/hraban/opus, and basically stripped of `libopusfile` dependency from the project.
> Remove opusfile dependency

- pkg/io/video/scaler_cgo.c
- pkg/io/video/scaler_cgo.go
NearestNeighbor | BoxSampling
--- | ---
```
$ CGO_CFLAGS="-march=native -O3" go test . -bench BenchmarkScale/Fast -benchmem -benchtime 3s
goos: linux
goarch: amd64
pkg: github.com/pion/mediadevices/pkg/io/video
BenchmarkScale/FastNearestNeighbor/480p/RGBA-4         	    1419	   2156141 ns/op	     716 B/op	       1 allocs/op
BenchmarkScale/FastNearestNeighbor/480p/I444-4         	     441	   7967492 ns/op	    3566 B/op	       1 allocs/op
BenchmarkScale/FastNearestNeighbor/1080p/RGBA-4        	    1574	   2248581 ns/op	     652 B/op	       1 allocs/op
BenchmarkScale/FastNearestNeighbor/1080p/I444-4        	     426	   8358253 ns/op	    3687 B/op	       1 allocs/op
BenchmarkScale/FastBoxSampling/480p/RGBA-4             	     559	   6228782 ns/op	    8317 B/op	       1 allocs/op …
```
> Add box sampling scaler

- pkg/frame/yuv.c
- pkg/frame/yuv.go
- pkg/frame/yuv_cgo.go
- pkg/frame/yuv_nocgo.go
- pkg/frame/yuv_test.go
Go
```
$ CGO_ENABLED=0 go test . -bench . -benchtime 5s
BenchmarkDecodeYUY2/640x480-4               7041       889,028 ns/op    
BenchmarkDecodeYUY2/1920x1080-4              883     6,616,224 ns/op   
```
CGO
```
$ go test . -bench . -benchtime 5s
BenchmarkDecodeYUY2/640x480-4              12721       502,289 ns/op    
BenchmarkDecodeYUY2/1920x1080-4             1694     3,451,253 ns/op   
```
CGO with gcc optimization
```
$ CGO_CFLAGS="-march=native -O3" go test . -bench . -benchtime 5s
BenchmarkDecodeYUY2/640x480-4              39645       164,450 ns/op    
BenchmarkDecodeYUY2/1920x1080-4             4682     1,195,134 ns/op   
```
Fixes #103
> Add CGO version of decodeYUY2

- examples/codecparam/README.md
- examples/codecparam/main.go
- pkg/codec/openh264/openh264.go
- pkg/codec/opus/opus.go
- pkg/codec/vpx/params.go
- pkg/codec/vpx/vpx.go
- pkg/prop/prop.go
I'd like to introduce it to vaapi codec (#102), which has a lot of low layer parameters and no API to get library default parameters like openh264 and vpx.
Fixes #105
> Support codec specific parameters

- .github/workflows/ci.yaml
- examples/codecparam/main.go
- pkg/codec/vaapi/framerate.go
- pkg/codec/vaapi/helper.c
- pkg/codec/vaapi/helper.h
- pkg/codec/vaapi/params.go
- pkg/codec/vaapi/vaapi.go
- pkg/codec/vaapi/vp8.go
- pkg/codec/vaapi/vp9.go
Using libva.
VP8/9 encoding by libva on post-Kabylake CPU (that has hardware acceleration) is faster than VP8 by libvpx.
fix #98
> Add hardware accelerated VP8/9 encoder

- go.mod
- go.sum
Handling of FdSet was wrong in blackjack/webcam.
Update blackjack/webcam to make it work with the number of
file descriptor more than 16.
Fixes #109
> Update blackjack/webcam to fix camera timeout

- pkg/codec/x264/bridge.h
- pkg/codec/x264/x264.go
Somehow x264 encoder got closed more than once when `cleanTrackers` is called in `getUserMedia`, and double free occurred:
```
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x264 [info]: profile Constrained Baseline, level 5.1
x264 [info]: frame I:1     Avg QP: 0.00  size:193627
x264 [info]: mb I  I16..4: 100.0%  0.0%  0.0%
x264 [info]: coded y,uvDC,uvAC intra: 100.0% 100.0% 100.0%
x264 [info]: i16 v,h,dc,p: 10% 17% 54% 19%
x264 [info]: i8c dc,h,v,p: 45% 31% 14% 11%
x264 [info]: kb/s:38725.40
munmap_chunk(): invalid pointer
SIGABRT: abort
PC=0x7f88ae9e53eb m=3 sigcode=18446744073709551610
goroutine 0 [idle]:
runtime: unknown pc 0x7f88ae9e53eb
stack: frame={sp:0x7f88abde1a40, fp:0x0} stack=[0x7f88ab5e2288,0x7f88abde1e88)
00007f88abde1940: …
```
> Avoid double free

- pkg/codec/vaapi/helper.c
- pkg/codec/vaapi/helper.h
- pkg/codec/vaapi/vaapi.go
- pkg/codec/vaapi/vaapi_unsupported.go
- pkg/codec/vaapi/vp8.go
- pkg/codec/vaapi/vp9.go
Make it buildable on unsupported environment.
Return error on runtime.
> codec/vaapi: return error on unsupported environment

- pkg/codec/vaapi/vp8.go
Fix not to use input surface as reference surface.
Fix flags of key-frame.
> codec/vaapi: fix VP8 reference surface usage

- mediadevices.go
- pkg/driver/wrapper.go
- pkg/prop/prop.go
- pkg/prop/prop_test.go
- pkg/prop/string.go
Caused panic at https://github.com/pion/mediadevices/blob/27d966611e1766d574ae78940df7c25656aaf428/pkg/prop/prop.go#L69-L70 when DeviceID was specified.
Compare DeviceID field on `FitnessDistance()` which was directly selected at upper layer.
follows up #168
> Select by DeviceID using StringConstraint

- mediadevices.go
- mediadevices_test.go
- pkg/prop/prop.go
- pkg/prop/prop_test.go
the constraints return by `selectBestDriver` should not be set to what the user specified, but instead the best property returned by the driver.
> Fix invalid constraints merging

- pkg/wave/decoder.go
- pkg/wave/decoder_bench_test.go
- pkg/wave/decoder_test.go
Unfortunately, in audio world, there's no clear standard for defining formats like fourcc for video. While defining our own consts for audio is fine, it's impractical when we're trying to integrate frameworks like avfoundation.
> Make raw audio decoder more practical

- pkg/prop/bool.go
- pkg/prop/prop.go
- pkg/prop/prop_test.go
Changes:
* Add bool constraint
* Add IsFloat, IsBigEndian, and IsInterleaved properties
I didn't implement BoolRange or BoolOneOf because they're not necessary since it's only a binary option, it can be done with just Bool.
> Add IsFloat, IsBigEndian, and IsInterleaved props

- pkg/io/video/detect_test.go
- pkg/io/video/throttle_test.go
This is a temporary workaround for https://github.com/pion/mediadevices/issues/198.
> Skip time related tests for Darwin

- pkg/driver/camera/camera_linux.go
According to https://www.kernel.org/doc/html/v4.10/media/uapi/v4l/pixfmt-yuv420.html, YU12 is equal to V4L2_PIX_FMT_YUV420 in v4l2 term. In fourcc, V4L2_PIX_FMT_YUV420 is equal to I420, V4L2_PIX_FMT_YUV420.
> Add V4L2_PIX_FMT_YUV420 support for Linux

- pkg/io/video/framebuffer.go
- pkg/io/video/framebuffer_test.go
This is an incremental effort to redesign the project. Frame copy is necessary for supporting a video broadcaster.
Benchmark:
```
goos: darwin
goarch: amd64
pkg: github.com/pion/mediadevices/pkg/io/video
BenchmarkCopyOptimized
BenchmarkCopyOptimized-4            9290            132430 ns/op             670 B/op          0 allocs/op
BenchmarkCopyNaive
BenchmarkCopyNaive-4                2613            446601 ns/op         3130664 B/op          4 allocs/op
PASS
ok      github.com/pion/mediadevices/pkg/io/video       5.769s
```
> Add frame Copier

- pkg/wave/buffer.go
- pkg/wave/buffer_test.go
This is an incremental effort to redesign the project. Wave's buffer is necessary for supporting an audio broadcaster.
Similar to https://github.com/pion/mediadevices/pull/209, but for audio.
> Add generic wave's Buffer

- mediadevices_test.go
- pkg/codec/codec.go
- pkg/codec/openh264/params.go
- pkg/codec/opus/params.go
- pkg/codec/vaapi/params.go
- pkg/codec/vpx/vpx.go
- pkg/codec/x264/params.go
- track.go
Depending on webrtc in codec is unnecessary. This PR is to clean up the dependency graph and make it more centralized, having the webrtc dependency in the root package only.
> Remove webrtc dependency in codec and its sub packages

- mediadevices_test.go
- pkg/codec/codec.go
- pkg/codec/openh264/params.go
- pkg/codec/opus/params.go
- pkg/codec/vaapi/params.go
- pkg/codec/vpx/vpx.go
- pkg/codec/x264/params.go
- track.go
Allowing users to implement RTPCodec will give users freedom to have a custom encoder with custom RTP payload. This is another incremental update toward the new design.
Use case:
```go
package main
import (
"github.com/pion/mediadevices"
"github.com/pion/mediadevices/pkg/codec/openh264"
"github.com/pion/mediadevices/pkg/codec/x264"
"github.com/pion/mediadevices/pkg/prop"
// Note: If you don't have a camera or microphone or your adapters are not supported,
//       you can always swap your adapters with our dummy adapters below.
// _ "github.com/pion/mediadevices/pkg/driver/videotest"
_ "github.com/pion/mediadevices/pkg/driver/camera" // This is required to register camera adapter
)
func main() {
var setting webrtc.SettingEngine
x264Params, _ := x264.NewParams()
openh264Params, _ := …
```
> Replace Name with RTPCodec in codec builder

- pkg/io/audio/detect.go
- pkg/io/audio/detect_test.go
This allows us to not need pass audio metadata manually. Consequently, users who want to transform audio can implement their transformation easily.
> Add audio change detection

- mediadeviceinfo.go
- mediastream.go
- mediastream_test.go
- track.go
Changes:
* Add unit tests for mediastream
* Remove webrtc.RTPCodecType dependency in mediastream
* Add Kind to Tracker interface
> Use MediaDeviceInfo instead of webrtc.RTPCodecType

- pkg/codec/codec.go
Embedded struct provides more future compatibility than type alias.
> Switch from type alias to embedded struct

- pkg/driver/camera/camera_linux.go
Speed up camera latency. On raspberry pi 3, the latency goes down from 3-5 seconds to <1 second with this change.
> Remove buffer in linux camera

- meta.go
- meta_test.go
Since broadcaster has a ring buffer, we can take advantage of this property to read the meta data for video/audio without losing any data.
> Add meta reader helper

- pkg/driver/camera/camera_linux.go
Some cameras support a range of resolutions with step wise. The fix is to not only capture the highest resolutions but uses the step wise to determine if we can support the hardcoded standard resolutions, https://commons.wikimedia.org/wiki/File:Vector_Video_Standards2.svg. In the future, we should use a custom data structure to capture more resolutions that are outside of the listed standard resolutions.
> Fix step wise resolutions in linux camera

- .github/workflows/ci.yaml
- pkg/codec/mmal/bridge.h
- pkg/codec/mmal/mmal.go
- pkg/codec/mmal/params.go
Using mmal significantly boosts video fps by offloading the encoding work from CPU to GPU. On a Raspberry Pi 3, libx264 only gives 480p18, whereas mmal can give 720p30.
> Add mmal hardware video encoder support

- pkg/codec/vpx/vpx.go
VPX doesn't allow 0 duration. If 0 is given, vpx_codec_encode will fail with VPX_CODEC_INVALID_PARAM.
0 duration is possible because mediadevices first gets the frame meta data by reading from the source,
and consequently the codec will read the first frame from the buffer. This means the first frame won't
have a pause to the second frame, which means if the delay is <1 ms (vpx duration resolution), duration
is going to be 0.
This is only a temporary fix for now. The main issue is tracked here, https://github.com/pion/mediadevices/issues/250.
> Fix wrong duration in vpx due to buffer usage

- go.mod
- go.sum
- pkg/driver/microphone/microphone.go
- track.go
Partially resolves https://github.com/pion/mediadevices/issues/253
Changes:
* Use malgo.DeviceInfo to get the microphone metadata
* Move static buffering to the driver layer
> Remove some hardcoded microphone metadata

- pkg/driver/screen/screen.go
- pkg/driver/screen/x11_linux.go
- pkg/driver/screen/x11capture_linux.go
- pkg/driver/screen/x11capture_linux_test.go
Original x11 adapter uses ~40% less CPU usage than kbinani/screenshot.
Ideally, we should migrate 100% to kbinani/screenshot. But, the CPU
usage difference is substantial. In the future, we should look deeper
into kbinani/screenshot and try to improve it.
> Bring back x11 adapter for Linux build only

- meta.go
- pkg/io/video/detect.go
- pkg/io/video/detect_test.go
This PR adds an argument to the `video.DetectChanges` function to allow for frame rate variations as long as they are within the specified margin.  
Fixes #...
It addresses this comment: https://github.com/pion/mediadevices/blob/5d5001d0b43f1687741122ee66dd22b0542c6ebe/pkg/io/video/detect.go#L43
> Tolerate video frame rate variation in properties detector

- ioreader.go
- mediastream_test.go
- track.go
Changes:
* [BREAKING CHANGE] NewEncodedReader is renamed to NewEncodedIOReader
* NewEncodedReader now returns a non-standard buffer reader to give
more meta data such as sample count
> Add NewEncodedIOReader

- .github/workflows/ci.yaml
Add an automated license check to CI. Since we're using various third-party libraries, this automated check should help us in the long run.
Suggested by @at-wat: https://github.com/pion/mediadevices/pull/264#pullrequestreview-550878544
> Add license check to CI

- .github/workflows/ci.yaml
- .gitignore
- Makefile
- examples/Makefile
- pkg/io/video/convert_cgo.go
Changes:
* Make codec build command now is prefixed with "build"
* A new "test" command to make
* Add a Makefile for examples
> Add example compilation test to CI

- examples/archive/main.go
- examples/facedetection/main.go
- examples/rtp/main.go
- examples/webrtc/main.go
I420 format is a common format that's required by encoders. Therefore, the video pipeline is significantly faster than other formats since there's no format conversion.
> Switch default frame format to I420

- pkg/codec/vpx/vpx.go
The following error occurs when scaling up the video frames using transform function such as `video.Scale(width, height, video.ScalerFastBoxSampling)` with `width` or `height` greater than the original frame dimension:
```
vpx_codec_enc_config_set failed (8)
```
Although this block seems to work fine when scaling down the frame, it does not seem to be enough in this case:
```
if ec := C.vpx_codec_enc_config_set(e.codec, e.cfg); ec != C.VPX_CODEC_OK {
return 0, fmt.Errorf("vpx_codec_enc_config_set failed (%d)", ec)
}
```
Creating and initializing a new codec object seem necessary.
> Fix VPX_CODEC_INVALID_PARAM on resolution change

- examples/facedetection/main.go
- pkg/avfoundation/AVFoundationBind/AVFoundationBind.m
Attempt to fix the MacOS integrated camera pixel format issues.
The integrated camera on my 2018 Macbook Pro supports the following pixel formats:
```
[avfoundation @ 0x7f8e3a808200] Supported pixel formats:
[avfoundation @ 0x7f8e3a808200]   uyvy422
[avfoundation @ 0x7f8e3a808200]   yuyv422
[avfoundation @ 0x7f8e3a808200]   nv12
[avfoundation @ 0x7f8e3a808200]   0rgb
[avfoundation @ 0x7f8e3a808200]   bgr0
```
I was only able to find the correct mapping for the YUY2 pixel format and it fixed my issue. If anyone knows the other mappings I can update this PR.
Fixes #287
> Add AVBindFrameFormatYUY2 mapping in AVFoundationBind

- pkg/avfoundation/AVFoundationBind/AVFoundationBind.h
- pkg/avfoundation/AVFoundationBind/AVFoundationBind.m
- pkg/avfoundation/avfoundation_darwin.go
- pkg/frame/const.go
- pkg/frame/yuv.go
- pkg/frame/yuv_test.go
Changes:
* Add logging for unincluded raw frame formats
* Add NV12 support for avfoundation
* Fix wrong Cb and Cr order in NV21
Possibly resolves https://github.com/pion/mediadevices/issues/292
> Add formats and logging to AVFoundation backend

- pkg/avfoundation/AVFoundationBind/AVFoundationBind.m
`NV21` is not `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange`.
Both `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange` and `kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange` are `NV12`.
https://github.com/FFmpeg/FFmpeg/blob/a7f841718ff93e3143f218cfdc27d1764024b0eb/libavutil/hwcontext_videotoolbox.c#L44-L45
> Fixes pixel format mapping in avfoundation

- pkg/codec/codec.go
- pkg/codec/opus/opus.go
- pkg/codec/opus/params.go
- pkg/codec/opus/params_test.go
- pkg/driver/microphone/microphone.go
- track.go
To avoid buffering audio data multiple times, remove buffer from
malgo audio driver and pass expected codec latency as a codec
parameter.
> Fix audio codec latency handling

- Makefile
```
go: warning: "pkg/..." matched no packages
```
> Fix build test target without CGO

- pkg/codec/internal/codectest/codectest.go
- pkg/codec/mmal/mmal_test.go
- pkg/codec/openh264/openh264.go
- pkg/codec/openh264/openh264_test.go
- pkg/codec/opus/opus.go
- pkg/codec/opus/opus_test.go
- pkg/codec/vaapi/vaapi_test.go
- pkg/codec/vaapi/vp8.go
- pkg/codec/vaapi/vp9.go
- pkg/codec/vpx/vpx.go
- pkg/codec/vpx/vpx_test.go
- pkg/codec/x264/x264_test.go
`Video/AudioTrack.NewRTPReader()` internally closes encoder on error.
It caused double free if user closes reader after error.
> Allow double close of codecs

- pkg/codec/openh264/bridge.cpp
- pkg/codec/openh264/bridge.hpp
- pkg/codec/openh264/openh264.go
The golang image.YCbCr struct can contain fields of arbitrary stride
lengths, which don't necessarily match the field widths. This
patch passes the stride values from the image.YCbCr struct into
the OpenH264 encode calls.
> Fixing Stride Handling for OpenH264

- pkg/avfoundation/avfoundation_darwin.go
- pkg/driver/camera/camera_darwin.go
@lherman-cs, this fixes a goroutine leak:
```goroutine leak(s) detected: found unexpected goroutines:
[Goroutine 17 in state chan send, locked to thread, with github.com/pion/mediadevices/pkg/avfoundation.(*ReadCloser).dataCb on top of the stack:
goroutine 17 [chan send, locked to thread]:
github.com/pion/mediadevices/pkg/avfoundation.(*ReadCloser).dataCb(...)
/Users/eric/mediadevices/pkg/avfoundation/avfoundation_darwin.go:112
github.com/pion/mediadevices/pkg/avfoundation.onData(0xc00000e080, 0x1174d0040, 0x2f8720)
/Users/eric/mediadevices/pkg/avfoundation/avfoundation_callback_darwin.go:24 +0xb0
]```
> Release AVFoundation ReadCloser on camera close

- go.mod
- go.sum
- mediadevices_test.go
- pkg/driver/camera/camera_linux.go
- pkg/driver/videotest/dummy.go
- pkg/prop/prop.go
This PR updates the [webcam](https://github.com/blackjack/webcam ) module to `ba064708e1652773bdb71e0605a1819ef4fad2e7` which allows to set (and get) the video camera capture framerate based on the `FrameRate` value specified in `prop.Media`.
> Update webcam module to set the camera framerate

- pkg/codec/x264/bridge.h
- pkg/codec/x264/x264.go
> Implement forced keyframes for x264

- mediadevices_test.go
- pkg/driver/camera/camera_linux.go
- pkg/prop/prop.go
This PR addresses an issue introduced by changes from https://github.com/pion/mediadevices/pull/390: the video framerate was added as an explicit constraint to find a compatible driver. As `camera.Properties` currently does not have access to the list of available framerate no driver can be matched. Until this information can be retrieved it is better to not include the framerate in the fitness function. As a workaround, when a framerate is specified (i.e. > 0), a comparison between the desired value and the one reported by the device is performed and an error is returned when they are not equal.
> Remove video framerate as explicit constraint

- pkg/driver/camera/camera_linux.go
- pkg/driver/camera/camera_linux_test.go
- pkg/prop/prop.go
This PR adds a field to the `Video` and `VideoConstraints` to be able to set the timeout duration when reading frames from the video source. This field is not used in `fitnessDistance` and is only considered when set to a positive value. These changes should not modify the original behavior as the default value is kept to 5 seconds.
> Camera timeout duration as parameter

- pkg/codec/openh264/bridge.cpp
- pkg/codec/openh264/bridge.hpp
- pkg/codec/openh264/openh264.go
- pkg/codec/openh264/params.go
There's been a long-standing TODO comment in the bridge for OpenH264 to
remove hardcoding for the set of configurable parameters exposed by that
library. That patch does exactly that.
> Enable configuration of OpenH264 Encoder

- track.go
This PR aims to give access to copy frame feature of `Broadcaster` in high level functions such as `track.NewEncodedReader()`.
Today, `track.New*Reader()` functions forces to disable frames copy from Broadcaster. This is not convenient when you want to use high level API with multiple readers, leading to video artefacts on some codec/frame format combination.
This API is not very elegant but doesn't introduce any complex or breaking changes.
> Allow to enable frame copy on a video track

- pkg/avfoundation/avfoundation_darwin.go
- track.go
Closing a record session on macOS does not close the reader.
This PR fixes this by closing the channel used to read incoming video frames directly in the Close function.
Calling it in the data callback is not working because since the record session is closed, the callback will never be called again. So the reader will indefinitely wait for a incoming frame/the channel to be closed, which will never happen.
By fixing this, i have also discover a bug, where closing a peer connection with some tracks already closed triggers a panic due to the stop mechanism.
Fixes #379
> Fix closing a camera not closing the associated track

- pkg/io/broadcast.go
- pkg/io/video/broadcast_test.go
Fixes a nil pointer reference in the Broadcaster when using the `copyFrame` feature.
We were trying to copy the read buffer even if an error occured
> fix nil reference when a read error occur with copyFrame enabled

- pkg/io/video/convert.go
- pkg/io/video/convert_cgo.c
- pkg/io/video/convert_cgo.go
- pkg/io/video/convert_cgo.h
- pkg/io/video/convert_nocgo.go
- pkg/io/video/convert_test.go
Fixes a race condition in the i420 video converter leading to artefacts when used in concurrently.
A way to see it in action is to create 2 x264 video encoder for the same video track with a video source using i422 or i444 color space. This triggers a bug where we don't convert the entire image, we only resample it, probably to avoid unecessary memory allocation. But when multiple encoders uses this converter at the same time, it will resample multiple time with the same original sample ration, leading to weird artefacts.
There is probably 2 way to fix this:
- add locks to avoid concurrent modifications
- make a copy when doing destructive operation
I have implemented the later one in this PR since adding a lock would be difficult, necessitating to be aware of it everywhere the frame is …
> fix race condition in i420 video converter leading to video artefacts

- pkg/avfoundation/avfoundation_darwin.go
Allow to close multiple time an avfoundation. For now, when closing an alreacy closed VideoTrack comming from avfoundation leads to a panic (close of closed channel)
> allow to close the avfoundation device multiple time

- pkg/codec/opus/opus.go
Renaming the C bitrate setter function allow to be combatible with `gopkg.in/hraban/opus.v2` (an opus decoder package)
Fixes #362
> rename opus C function to be compatible with other opus modules

- pkg/driver/microphone/microphone.go
Prior to this, there's a chance you would close the chunk channel while malgo is trying to send on it. Instead, it's better to stop the malgo device and then close. That also means we need to discard chunks when trying to stop due to the buffered channel.
> Properly close microphone before malgo chunk channel

- track.go
- track_test.go
Fix the newly added PLI and FIR handling. An error has been introduce when merging the PR.
We were reading with an empty buffer, which lead to `io.ErrShortBuffer` error. This was causing the RTCP read loop to crash, but the track remained sending video, since the reading and writing loops were not linked.
A potentially breaking side effect was also the call to `track.OnEnded`, while the track didn't realy ended in facts.
I'm fixing this by using a buffer of 1500 bytes (from what I have found in different examples), and closing the track when read errors occurs.
> fix PLI and FIR handling, wrongly triggering track.OnEnded

- pkg/codec/internal/codectest/codectest.go
- pkg/codec/mmal/mmal_test.go
- pkg/codec/openh264/openh264_test.go
- pkg/codec/opus/opus.go
- pkg/codec/opus/opus_test.go
- pkg/codec/vaapi/vaapi_test.go
- pkg/codec/vpx/vpx_test.go
- pkg/codec/x264/x264_test.go
> Fix opus codec panic on read after close

- pkg/driver/microphone/microphone.go
This was causing issues with recording when miniaudio interpreted the latency on its own to 10ms.
> Utilize audio property latency in microphone AudioRecord

- .github/workflows/ci.yaml
- Makefile
DRI device appears on GitHub Actions runner but unusable. (`vainfo` errors as well)
Skip `pkg/codec/vaapi` on CI.
> Skip vaapi test on CI

- renovate.json
Same as https://github.com/pion/renovate-config/pull/2
> Disable updating minimum Go version in go.mod

- pkg/driver/camera/camera_darwin.go
- pkg/driver/camera/camera_darwin_test.go
- pkg/driver/camera/camera_linux.go
- pkg/driver/camera/camera_windows.go
- pkg/driver/microphone/microphone.go
- pkg/driver/screen/screen.go
- pkg/driver/screen/x11_linux.go
This PR exports the logic executed at startup to find and register cameras. This will allow us to discover cameras connected after our application has started.
> Expose device list update func

- track.go
- track_test.go
Occurs when read errors happen from a
driver source during a call to track.Bind()
Example of deadlock:
1. When a driver reader function has a read error immediately after being initialized: contrived example:
```golang
video.ReaderFunc(func() (image.Image, func(), error) {
return nil, nil, errors.New("Ahhhh")
})
```
2. Pion calls bind() on a track using that reader function.
3. Within NewRTPReader():
a. The reader function is wrapped to call track.onError if a read error is returned in newVideoTrackFromReader()
b. Read is called synchronously in detectCurrentVideoProp() in the function newEncodedReader()
c.  track.onError() is triggered within the bind function (so without this fix, the mutex lock on bind() will not yet be released, and would deadlock in track.onError())
> Fix deadlock in track.Bind()

- examples/go.sum
- go.mod
- pkg/driver/camera/camera_linux.go
From the Linux kernel documentation [here](https://linuxtv.org/downloads/v4l-dvb-apis/driver-api/v4l2-videobuf.html)
> As a practical rule, a minimum of two buffers are needed for proper streaming, and there is usually a maximum (which cannot exceed 32) which makes sense for each device.
This code updates the buffer size from 1 to 2 along with the frame skip logic. The side effect is much higher fps on all 3 of the cameras I've tested, presumably because the buffer is no longer a bottleneck, and there shouldn't be a risk of slowing down any streams.
> change buffer size to 2

- pkg/avfoundation/AVFoundationBind/AVFoundationBind.h
- pkg/avfoundation/AVFoundationBind/AVFoundationBind.m
- pkg/avfoundation/avfoundation_darwin.go
- pkg/driver/camera/camera_darwin.go
- pkg/driver/camera/camera_linux.go
- pkg/driver/driver.go
As it is currently implemented, the only way to identify a device plugged into a Darwin system is by `UID` even though many other forms of identification exist for each device, as explained in this [_Identifying a Device_](https://developer.apple.com/documentation/avfoundation/avcapturedevice) section of the AVFoundation documentation. This change exposes the `localizedName` and adds it as `Name` to the `avfoundation.Device` type struct. Additionally, the name is added to the `driver.Info` type struct so that it is included when registering a device.
While the `UID` that is currently registered for each device is helpful, it is not human readable, unlike `localizedName`. For example, when discovering the devices on a MacBook, the built in webcam's `UID` is a string of numbers, letters, …
> Expose name of devices along with UID for macOS

- go.mod
- go.sum
- pkg/driver/camera/camera_linux.go
This PR exposes the device name and bus info for Linux cameras.
> expose device name and bus info

- go.mod
- go.sum
- pkg/driver/camera/camera_linux.go
- pkg/driver/camera/camera_linux_test.go
- pkg/prop/prop.go
- pkg/prop/prop_test.go
This PR allows for retrieving and setting FPS properties on Linux cameras. Like FrameSize, `Discrete` and `Stepwise` FrameRate returns are supported.
A simple check is added in the `fitness` function to avoid adding fps comparisons on MacOS and Screen drivers.
Implementation depends on this [blackjack/webcam PR](https://github.com/blackjack/webcam/pull/58).
Update: fps pr for blackjack/webcam has been merged!
Make sure there are no regressions across platforms (fitness distance is not affected).
- linux webcam
- mac webcam
- linux screen
- Added unit tests for `float` and `FrameRate` matching in `prop_test.go`. Includes cases where FPS is not available.
- Added unit test for `calcFramerate` in `camera_linux_test.go`.
- No regressions in other prop.go and camera_linux tests.
> Add FPS Props for Linux Cameras

- README.md
Added to the FAQ to mention GetDisplayMedia if using driver/screen in the section explaining solutions to the error that gets throne if you don't make that swap in example code.
Fixes #...
> Update README.md to include mention of GetDisplayMedia

- pkg/avfoundation/AVFoundationBind/AVFoundationBind.h
- pkg/avfoundation/AVFoundationBind/AVFoundationBind.m
- pkg/avfoundation/avfoundation_darwin.go
- pkg/frame/decode.go
Add YUYV to supported video formats; used to be implicitly supported under YUY2. That meant the user had to know to ask for YUY2 decoding when using a YUYV device; this PR allows the user to specify YUYV instead.
> Add YUYV to supported video formats

- pkg/driver/microphone/microphone.go
A tiny change to the Initialize function in the Microphone driver ensuring that the device name is included in the driver.Info struct.
> Added Name in driver.Info to Microphone driver

- pkg/driver/camera/camera_linux.go
This PR fixes an issue where properties are skipped if framerate querying is not supported by the driver. To fix this we simply add width, height, and format if `GetSupportedFramerates` errors or returns an empty list.
> Add props even if framerate is not supported by the driver

- go.mod
- go.sum
- pkg/driver/microphone/microphone.go
- Also log when we do not support a malgo format (e.g. the iota value)
> Update malgo to v0.11.11-0.20231225022531-dd505cb7efd5 for a macOS microphone fix

- pkg/avfoundation/AVFoundationBind/AVFoundationBind.m
On macOS Sonoma, using the Logitech C922 Pro webcam, NV12 frames seem to come with a default min amount of padding for smaller resolutions e.g. 160x90. This would result in smaller resolution NV12 images outputting like this:
This change crops the data—making sure it is packed tightly—so that the `decodeNV12` precondition can be preserved.
> Add fix that strips unexpected padding for NV12 frames

- examples/go.sum
- go.mod
- go.sum
Simple webcam bump to `0.6.1` -- fixes issue with mmap flags causing streams to fail for some Linux drivers.
See webcam commit [here](https://github.com/blackjack/webcam/commit/15347780752e4f6e9767d4e8b15a60038dc27f85).
> Bump webcam dependency

- .github/workflows/ci.yaml
- Isolate local homebrew cache directory from the host environment
- Weekly refresh homebrew cache
> Improve ARM Darwin CI stability

- .github/workflows/ci.yaml
Coverage status is failing due to https://github.com/pion/mediadevices/pull/589#issuecomment-2430667632
> Update CI Go versions

- .github/workflows/ci.yaml
Explicitly install libx11-dev and libxext-dev
> Fix dependency installation on the latest actions runner

- pkg/codec/vpx/vpx.go
- pkg/codec/vpx/vpx_test.go
There is an issue with VPX encoder that using `time.Now().Nanosecond() / 1000000` as the timestamp marker and make the timestamp is not monotonic and there is a potential issue the frame duration become negative and make the encoding failed.
Check the new test included in this PR to reproduce the issue.
Updated:
I just saw this issue seems similar to #603 I can close this one and merge that one if needed.
> Fix the VPX encoder is not properly handling the frame timestamp

- mediastream_test.go
- track.go
In previous pr #612, method EncoderController is added on VideoTrack and AudioTrack.
This PR adds this method in Track interface as well.
> Add EncoderController() codec.EncoderController in Track interface.

- track.go
Fixes: #633
Here the signalCh could have been closed by another goroutine, we should
use returned signalCh from `track.removeActivePeerConnection()` to close
the channel.
Actually, I don't know why we need to close the signalCh, we're using it
to send over the doneCh, why ever close it?
> fix track.unbind panic

- mediastream_test.go
- pkg/codec/codec.go
- pkg/driver/vncdriver/vnc/client.go
- pkg/driver/vncdriver/vnc/server_messages.go
- pkg/io/audio/broadcast.go
- pkg/io/broadcast.go
- pkg/io/broadcast_test.go
- pkg/io/reader.go
- pkg/io/video/broadcast.go
- pkg/prop/duration.go
- pkg/prop/float.go
- pkg/prop/format.go
- pkg/prop/int.go
- pkg/prop/prop.go
- pkg/prop/string.go
Applies go modernization suggestions, see https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize for more details.
N/A
> Apply go modernize
