pion/mediadevices

- camera/camera_linux.go
- frame/README.md
- frame/const.go
- frame/decode.go
- frame/frame.go
- frame/yuv.go
> Switch from using a compressed format to an uncompressed format

- camera/camera_linux.go
> Allow camera to accept YUYV and NV21 formats

- pkg/codec/vpx/vpx.go
> Implement vpx (VP8 and VP9) encoder

- examples/simple/main.go
Now, it should work both on Firefox and Chrome.
> Add Firefox and VP8 support to the simple example

- mediadevices.go
- track.go
Add a constructor directly from lists of codecs.
It makes MediaDevices capable for non-WebRTC purposes as same as the Web API.
Closes #16
> Add MediaDevicesFromCodecs

- driver.go
- pkg/driver/camera/camera_linux.go
- pkg/driver/microphone/microphone_linux.go
Resolves https://github.com/pion/mediadevices/issues/22
Created 2 new directories under driver, camera and microphone. Moved camera_linux.go and microphone_linux.go appropriately. Imported driver/camera and driver/microphone by default.
> Group Adapters by their categories

- examples/simple/main.go
- pkg/codec/codec.go
- pkg/codec/openh264/openh264.go
- pkg/codec/opus/opus.go
- pkg/codec/registrar.go
- pkg/codec/vpx/vpx.go
- pkg/prop/prop.go
- track.go
Add CodecParameters, which stores general encoding parameters,
to MediaTrackConstraints.
Fixes #29
> Add CodecParameters

- examples/transform/README.md
- examples/transform/main.go
- mediadevices.go
- mediastreamconstraints.go
- pkg/io/audio/audio.go
- pkg/io/video/video.go
- track.go
I had to update the `MediaStreamConstraints` so that the users will be able to use the APIs nicely.
Resolves https://github.com/pion/mediadevices/issues/31.
> Add custom video/audio transforms

- track.go
Resolves https://github.com/pion/mediadevices/issues/32
> Fix Track's ID and Label are swapped

- driver.go
- go.mod
- go.sum
- mediadeviceinfo.go
- mediadevices.go
- pkg/driver/camera/camera_linux.go
- pkg/driver/driver.go
- pkg/driver/manager.go
- pkg/driver/microphone/microphone_linux.go
- pkg/driver/wrapper.go
- pkg/prop/prop.go
Implement EnumerateDevices and register all devices
Select media with DeviceID property
Closes #38
> Implement EnumerateDevices and DeviceID property

- examples/simple/main.go
- examples/transform/main.go
> Use AddTransceiverFromTrack in examples

- pkg/codec/vpx/vpx.go
Set frame timestamp by the system time to make encoder's bitrate
calcuation correct for variable framerate.
> Fix vpx frame timestamp

- examples/rtp-send/README.md
- examples/rtp-send/main.go
- go.mod
- mediastream.go
- track.go
- Fix LocalTrack interfacing
- Add rtp-send example
> Fix LocalTrack interfacing

- driver.go
- examples/screenshare/README.md
- examples/screenshare/main.go
- mediadeviceinfo.go
- mediadevices.go
- pkg/driver/camera/camera_linux.go
- pkg/driver/const.go
- pkg/driver/driver.go
- pkg/driver/manager.go
- pkg/driver/manager_test.go
- pkg/driver/microphone/microphone_linux.go
- pkg/driver/screen/x11_linux.go
- pkg/driver/screen/x11capture_linux.go
- pkg/driver/wrapper.go
- pkg/frame/const.go
> Add screen capture device for Linux

- mediadevices.go
- pkg/driver/driver.go
- pkg/driver/microphone/microphone_linux.go
- pkg/driver/wrapper.go
Make system default device selected by default.
Fixes #47
> Add driver priority information

- driver.go
- examples/rtp-send/main.go
- examples/screenshare/main.go
- examples/simple/main.go
* Update examples to import adapters explicitly
* Remove default adapters to be imported implicitly
> Remove default adapters

- examples/simple/main.go
- pkg/driver/audiotest/dummy.go
- pkg/driver/videotest/dummy.go
Which work similar to GStreamer audiotestsrc, videotestsrc.
> Add audiotest and videotest driver

- pkg/driver/wrapper.go
- pkg/driver/wrapper_test.go
* Fix unguarded VideoRecord and AudioRecord
* Properties returns nil when driver is closed
* Add Video/Audio adapter wrapper state tests
> Fix Video/Adapter wrapper state guards

- pkg/codec/vpx/vpx.go
Store Go pointers in C memory by C code and unref before return.
https://golang.org/cmd/cgo/#hdr-Passing_pointers
>  Go code may not store a Go pointer in C memory. C code may store Go pointers in C memory, subject to the rule above: it must stop storing the Go pointer when the C function returns.
> Fix cgo pointer usage

- examples/screenshare/main.go
- examples/transform/main.go
- go.mod
- go.sum
- pkg/driver/screen/x11_linux.go
- pkg/frame/const.go
- pkg/io/video/convert.go
Resolves https://github.com/pion/mediadevices/issues/46
> Add support for non-YCbCr input to ToI420

- pkg/io/video/throttle.go
- pkg/io/video/throttle_test.go
> Add video throttle transform

- pkg/codec/vpx/vpx.go
- pkg/driver/screen/x11_linux.go
- pkg/driver/screen/x11capture_linux.go
- pkg/driver/screen/x11capture_linux_test.go
- pkg/io/video/convert.go
branched from #54 non-ycbcr-input
> Optimize image processing

- pkg/io/video/scale.go
Update bounds before image allocation.
> Fix size update of aspect-ratio-fixed scaling

- pkg/codec/openh264/openh264.go
- pkg/codec/vpx/vpx.go
CGO based codecs caused segmentation fault due to the race condition
of Close() and Read().
> Fix race condition in codecs

- examples/rtp-send/README.md
- examples/rtp-send/vp8.sdp
Caps setting was missing.
Also add a command to listen RTP using VLC.
> Fix RTP-send GStreamer command and add VLC

- .github/workflows/ci.yaml
- pkg/io/video/convert.go
- pkg/io/video/convert_cgo.go
- pkg/io/video/convert_nocgo.go
- Add build test without CGO
- Declare functions selected at runtime for non-CGO environment
> Fix build without CGO

- go.mod
- pkg/driver/microphone/microphone_windows.go
Using classic waveInOpen API.
Some of the part is stub, but it works for default input device.
Future works: enum devices, detect and handle microphone device disconnection, get actual props
fixes #83
> Add microphone driver for Windows

- README.md
- pkg/driver/camera/camera_windows.cpp
- pkg/driver/camera/camera_windows.go
- pkg/driver/camera/camera_windows.hpp
~Image size is fixed to 640x480.~
~Pixel format is fixed to RGB.~
~temporary branched from #83~ rebased
fix #26
> Add windows video

- pkg/io/video/convert.go
- pkg/io/video/convert_cgo.go
- pkg/io/video/convert_nocgo.go
- pkg/io/video/convert_test.go
Switch on build time and define `hasCGOConvert` as a const.
> Simplify CGO switch of video converters

- .github/workflows/ci.yaml
- examples/simple/main.go
- pkg/codec/x264/bridge.h
- pkg/codec/x264/params.go
- pkg/codec/x264/x264.go
**Description**
* Add x264 codec (requires `libvpx-dev` to be installed)
* Support KeyFrameInterval
* Support Quality rate control
> Add X264 encoder

- examples/codecparam/README.md
- examples/internal/jsfiddle/audio-and-video/demo.css
- examples/internal/jsfiddle/audio-and-video/demo.details
- examples/internal/jsfiddle/audio-and-video/demo.html
- examples/internal/jsfiddle/audio-and-video/demo.js
- examples/internal/jsfiddle/video/demo.css
- examples/internal/jsfiddle/video/demo.details
- examples/internal/jsfiddle/video/demo.html
- examples/internal/jsfiddle/video/demo.js
- examples/screenshare/README.md
- examples/simple/README.md
- examples/transform/README.md
Load code from GitHub repository.
Fixes #115
> Manage jsfiddle code in tree

- examples/codecparam/main.go
- pkg/codec/vaapi/params.go
- pkg/codec/vaapi/vp8.go
- pkg/codec/vaapi/vp9.go
> codec/vaapi: calculate max bit-rate from BaseParam

- go.sum
- mediadevices_test.go
- pkg/codec/codec.go
- pkg/codec/openh264/openh264.go
- pkg/codec/openh264/params.go
- pkg/codec/opus/opus.go
- pkg/codec/opus/params.go
- pkg/codec/vaapi/params.go
- pkg/codec/vaapi/vp8.go
- pkg/codec/vaapi/vp9.go
- pkg/codec/vpx/vpx.go
- pkg/codec/x264/params.go
- pkg/codec/x264/x264.go
- track.go
This is the initial step for supporting #119
> Add Rate limiting interface

- README.md
- pkg/driver/camera/camera_linux.go
- pkg/frame/const.go
- pkg/frame/decode.go
- pkg/frame/yuv.c
- pkg/frame/yuv_cgo.go
- pkg/frame/yuv_nocgo.go
- pkg/frame/yuv_test.go
> driver/camera: support UYVY camera

- pkg/driver/screen/x11capture_linux.go
> driver/screen: support X11 16 bit color frame buffer

- mediadevices.go
- sampler.go
- track.go
Resolves https://github.com/pion/mediadevices/issues/141
Before:
After:
> Refractor track to be more DRY

- track.go
> Fix formatting

- mediadevices_test.go
- pkg/codec/opus/opus.go
- pkg/driver/audiotest/dummy.go
- pkg/driver/microphone/microphone_linux.go
- pkg/driver/microphone/microphone_windows.go
- pkg/io/audio/audio.go
- pkg/io/audio/beep.go
- pkg/wave/float32.go
- pkg/wave/float32_test.go
- pkg/wave/int16.go
- pkg/wave/int16_test.go
- pkg/wave/wave.go
- pkg/wave/wave_test.go
> Define audio data interface

- .github/workflows/renovate-go-mod-fix.yaml
> Don't update examples/go.mod on renovate-go-mod-fix

- pkg/codec/vaapi/vp8.go
Previous reference frame update sequence was borrowed from
an example in libva-utils, however the quality of the output
was not good (block noised).
This commit disables alternate frame and updates golden frame only
on keyframe. It doesn't enable full referencing feature of VP8, but
ffmpeg vaapi encoder looks also not fully using golden frame and
alternate frame.
> codec/vaapi: fix reference frame update

- internal/codec/measurement.go
- internal/codec/measurement_test.go
- improve accuracy of bitrate calculation
- reduce test input timing error
fix #144
> Fix bitrate measurement stability

- examples/facedetection/main.go
- examples/rtp-send/main.go
- examples/simple/main.go
- mediadevices.go
- mediadevices_test.go
- mediastreamconstraints.go
- pkg/prop/duration.go
- pkg/prop/float.go
- pkg/prop/format.go
- pkg/prop/int.go
- pkg/prop/prop.go
- pkg/prop/prop_test.go
- track.go
> Support ranged/exact/oneof media constraints

- .github/workflows/ci.yaml
- pkg/io/video/throttle_test.go
Fix unstable test on OSX environment
Part of #174
> Add darwin CI job

- README.md
- pkg/avfoundation/.gitignore
- pkg/avfoundation/AVFoundationBind.xcodeproj/project.pbxproj
- pkg/avfoundation/AVFoundationBind.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- pkg/avfoundation/AVFoundationBind.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- pkg/avfoundation/AVFoundationBind.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- pkg/avfoundation/AVFoundationBind.xcodeproj/xcshareddata/xcschemes/AVFoundationBind.xcscheme
- pkg/avfoundation/AVFoundationBind/AVFoundationBind.h
- pkg/avfoundation/AVFoundationBind/AVFoundationBind.m
- pkg/avfoundation/avfoundation_callback_darwin.go
- pkg/avfoundation/avfoundation_darwin.go
- pkg/driver/camera/camera_darwin.go
* Add avfoundation Go and C bindings
* Add darwin camera adapter
> Add darwin camera support

- pkg/wave/decoder.go
- pkg/wave/decoder_test.go
* Add Int16Interleaved and Int16NonInterleaved formats
* Add Float32Interleaved and Float32NonInterleaved formats
* Add unit tests
> Add raw audio decoder

- pkg/wave/decoder.go
- pkg/wave/decoder_bench_test.go
* Add a minor fix for non interleaved formats
* Add decoder benchmark for host vs non-host endian
> Add fast wave decoder

- pkg/codec/opus/opus.go
- pkg/codec/opus/params.go
- pkg/driver/microphone/microphone_linux.go
- pkg/driver/microphone/microphone_windows.go
- pkg/io/audio/buffer.go
- pkg/io/audio/mixer.go
- pkg/prop/prop.go
- pkg/wave/float32.go
- pkg/wave/float32_test.go
- pkg/wave/int16.go
- pkg/wave/int16_test.go
- pkg/wave/int64.go
- pkg/wave/mixer/mixer.go
- pkg/wave/mixer/mixer_test.go
- pkg/wave/wave.go
Usually int16 is sound system native format.
> Opus support int16

- pkg/io/audio/buffer.go
- pkg/io/audio/buffer_test.go
- pkg/io/audio/mixer.go
- pkg/io/audio/mixer_test.go
SamplingRate field was not copied and Len of Buffer output was wrong.
related #182
> Fix audio transforms

- pkg/io/video/detect.go
- pkg/io/video/detect_test.go
This will flexibly detect changes whenever the source transforms.
Solve the video side, https://github.com/pion/mediadevices/issues/171
> Add property change detection for video pipeline

- .github/workflows/ci.yaml
Update CI to use 2 newest Go versions.
> Update CI to use Go 1.15 and 1.14

- pkg/frame/const.go
- pkg/frame/decode.go
- pkg/frame/frame.go
Hid ReaderFunc and cleaned up some documentations as they're redundant.
> Frame package refactor

- mediadevices.go
- pkg/prop/bool.go
- pkg/prop/duration.go
- pkg/prop/float.go
- pkg/prop/format.go
- pkg/prop/int.go
- pkg/prop/prop.go
- pkg/prop/prop_test.go
- pkg/prop/string.go
Many times users tried to run the example and found that it couldn't find a driver, the error message it has been confusing and too generic. This PR will let users know what the library can discover, this way we can isolate the issues a lot faster.
> Add human readable driver not found error message

- pkg/io/broadcast.go
- pkg/io/reader.go
- pkg/io/video/broadcast.go
- pkg/io/video/broadcast_test.go
Changes:
* Add generic io.Reader
* Add generic broadcaster
* Add specialize video broadcaster
* Add ring buffer to avoid frames being dropped
> Add pull-based Broadcaster

- pkg/io/broadcast_test.go
- pkg/io/video/broadcast_test.go
Changes:
* Move core broadcast tests to io
* Add targeted tests for video.Broadcast
> Move current broadcast test to io

- pkg/wave/buffer.go
- pkg/wave/buffer_test.go
* Add unit test to check internal buffer integrity
* Fix unstored audio in internal buffer
> Fix unstored audio

- pkg/io/audio/broadcast.go
- pkg/io/audio/broadcast_test.go
Similar to https://github.com/pion/mediadevices/pull/214, but for audio.
This PR depends on https://github.com/pion/mediadevices/pull/224.
> Add audio pull-based broadcast

- pkg/driver/camera/camera_linux.go
/dev/v4l/by-path doesn't return all available devices. So, to make sure that we include all available devices, the list of devices will also complement with /dev/video*.
> Fix undiscovered some camera devices

- codec.go
- examples/go.mod
- examples/http/main.go
- examples/webrtc/main.go
- mediadevices.go
- mediadevices_test.go
- mediastream.go
- mediastream_test.go
- mediastreamconstraints.go
- sampler.go
- source.go
- track.go
- track_test.go
Changelog:
* Better support for non-webrtc use cases
* Enable multiple readers
* Enhance codec selectors
* Update APIs to reflect on the new v3 webrtc design
* Cleaner APIs
> New mediadevices design

- .github/workflows/ci.yaml
- internal/codec/measurement_test.go
Related: https://github.com/pion/mediadevices/issues/198
> Skip bitrate measure test on darwin

- pkg/codec/vpx/vpx_test.go
> Add test for vpx input image size change

- pkg/avfoundation/AVFoundationBind/AVFoundationBind.m
- pkg/avfoundation/avfoundation_callback_darwin.go
- pkg/driver/camera/camera_bench_test.go
- pkg/driver/camera/camera_darwin_test.go
- pkg/frame/yuv_cgo.go
- pkg/frame/yuv_nocgo.go
This fixes panic when using `NV12` frame on macos platform.
Fixes #292
> Fixes avfoundation panic when using NV12 frame

- pkg/driver/screen/x11capture_linux.go
This allows compilation on 32-bit devices.
> Fix 32-bit usage of x11capture_linux

- pkg/driver/screen/x11capture_linux.go
Wasn't able to test 16-bit but did test 24-bit on a qemu raspi3
> Support RGB24 and RGB16 in x11capture_linux

- pkg/driver/camera/camera.go
- pkg/driver/camera/camera_linux.go
See https://github.com/pion/mediadevices/pull/304
> combine reallink and label for cameras on linux

- pkg/driver/camera/camera.go
- pkg/driver/camera/camera_linux.go
- pkg/driver/camera/camera_linux_test.go
Fix https://github.com/pion/mediadevices/pull/311/files#r589148142
> Fix linux camera label rule document

- pkg/codec/openh264/bridge.cpp
- pkg/codec/openh264/bridge.hpp
- pkg/codec/openh264/openh264.go
This PR adds the ability to force the next frame to be a keyframe.
> Implemented ForceKeyFrame for openh264 encoder

- pkg/driver/camera/camera_linux_test.go
Make it testable on a computer with real cameras.
Fix order of test result.
> Stabilize pkg/driver/camera.TestDiscover

- track.go
The `unbind` function was borrowing the track mutex more than it should. We need to borrow only while searching for active peer connection.
Keeping the lock while waiting for the end of the peer connection leads to dead lock with other parts of the code such as track's error handling code.
Fixes #336
> Fix dead lock when closing peer connection with running tracks

- pkg/codec/vpx/params.go
- pkg/codec/vpx/vpx.go
- pkg/codec/vpx/vpx_test.go
This PR implements Key Frame requests for VPX.
My goal is to use this when we receive a PLI packet to send a fresh new Key Frame.
> Implements RequireKeyFrame for VPX codec

- track.go
Just replaced VideoTrack with AudioTrack
> Fixed Comment Error

- examples/vnc/README.md
- examples/vnc/main.go
- pkg/driver/vncdriver/vnc/LICENSE
- pkg/driver/vncdriver/vnc/README.md
- pkg/driver/vncdriver/vnc/client.go
- pkg/driver/vncdriver/vnc/client_auth.go
- pkg/driver/vncdriver/vnc/color.go
- pkg/driver/vncdriver/vnc/encoding.go
- pkg/driver/vncdriver/vnc/pixel_format.go
- pkg/driver/vncdriver/vnc/pointer.go
- pkg/driver/vncdriver/vnc/server_messages.go
- pkg/driver/vncdriver/vncdriver.go
>  Add VNC as a video source

- mediastream_test.go
- track.go
This was added in pion/webrtc@f644649
> Add RID to Track and baseTrack

- pkg/driver/vncdriver/vnc/encoding.go
- pkg/driver/vncdriver/vncdriver.go
Implement the CursorEncoding protocol of VNC
实现VNC的CursorEncoding协议，隐藏远端桌面鼠标
Fixes #...
> Implement the CursorEncoding protocol of VNC

- pkg/driver/microphone/microphone.go
根据DeviceID打开mic，修复多个mic设备的不能选择的bug。
Open microphone with DeviceID. fix the bug that multiple mic devices cannot be selected.
Fixes #...
> fix : Turn on the microphone with the current device id

- pkg/codec/openh264/openh264_static.go
> fix:  Fix compilation error on arm64 Mac

- .github/workflows/ci.yaml
- pkg/wave/buffer_test.go
Upgrade go versions for the test runners
Fixes #415
> Upgrade CI go versions for tests

- renovate.json
Update go.mod under examples by Renovate.
> Do not ignore dependencies under examples

- renovate.json
Ignore update like https://github.com/pion/mediadevices/pull/431
> Ignore self dependency from examples

- pkg/driver/camera/camera_windows.cpp
Fix for having multiple cameras in Windows
Fixes #...
> Fix for having multiple cameras in Windows

- .github/workflows/ci.yaml
> Add CI for M1 Mac

- pkg/driver/manager.go
- pkg/driver/manager_test.go
I've run into race conditions accessing `Manager` concurrently. This PR adds tests and fixes for race conditions.
> handle race conditions + add test for Manager.Register

- pkg/codec/codec.go
> Align H265 payloadType in NewRTPH265Codec with RegisterDefaultCodecs

- pkg/codec/bitrate_tracker.go
- pkg/codec/bitrate_tracker_test.go
This is used to track the encoded bitrate, and based on that, the dynamic QP algorithm can adjust QP based on target bitrate
> [CODEC] Add encoder bitrate tracker
